FROM docker.io/apache/airflow:2.3.3

# Switch to the airflow user
USER airflow

# Instala la biblioteca python-dotenv usando la capacidad de instalación de Airflow
RUN pip install --no-cache-dir python-dotenv


